public enum ProgressSave
{
    INIT_GAME,
    SEE_BLOCK_VILLAGE_EXIT,
    CLEANED_HOUSE,
    LEVEL_1_COMPLETED,
    LEVEL_2_COMPLETED,
    LEVEL_3_COMPLETED,
    LEVEL_4_COMPLETED,
    LEVEL_1_STARTED
} 
